avg_smogon/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('avg_smogon/', views.avg_smogon_view, name='avg_smogon'),
    path('my_smogon_script', views.my_smogon_script, name='my_smogon_script'),
]

character_data/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('character_data/', views.character_data, name='character_data'),
    path('', views.main, name='main'),
    path('details/<str:fullname>/', views.details, name='details'),
    path('muse/', views.muse, name='muse'),
]

my_daystar_database/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('character_data.urls')),
    path('smogon/', include('avg_smogon.urls')),
    path('admin/', admin.site.urls),
]

avg_smogon/models.py
from django.db import models

# Create your models here.

character_data/models.py
from django.db import models
genderPossibilities = {
    "Female": "Female",
    "Male": "Male",
    "Non-binary": "Non-binary",
    "Other": "Other",
    "Feminine-aligned": "Feminine-aligned",
    "Masculine-aligned": "Masculine-aligned",
}
rolePossibilities = {
    "Staff": "Staff",
    "Subject": "Subject",
}
specificRolePossibilities = {
    "Docile": "Docile",
    "Lahde": "Lahde",
    "Cronus": "Cronus",
    "Halcyon": "Halcyon",
    "Nonviable": "Nonviable",
    "Scientist": "Scientist",
    "Medical Staff": "Medical Staff",
    "Intern": "Intern",
}
musePossibilities = {
    1: "Red",
    2: "Orange",
    3: "Yellow",
    4: "Green",
    5: "Blue",
}
class Character(models.Model):
    fullname = models.CharField(max_length=255)
    role = models.CharField(choices=rolePossibilities,max_length=50)
    age = models.IntegerField()
    subjectNumber = models.IntegerField()
    gender = models.CharField(choices=genderPossibilities,max_length=50)
    specificRole = models.CharField(choices=specificRolePossibilities,max_length=50)
    orientation = models.CharField(max_length=50)
    allosexual = models.BooleanField()
    species = models.CharField(max_length=50)
    documentLink = models.CharField(max_length=150)
    submitted = models.BooleanField()
    muse = models.IntegerField(choices=musePossibilities)
    def __str__(self):
        return self.fullname

avg_smogon/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
import requests, json
from collections import Counter
import time
# from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

def avg_smogon_view(request):
    return render(request, 'avg_smogon.html')
def my_smogon_script(request):
    if request.method == 'POST':
        da_pokemon_needed = request.POST.get('pokemon_input', '')
        result = smogon_actual_script(da_pokemon_needed)
        context = {"result": result}
        return render(request, 'avg_smogon.html', context)
    else:
        # This is the GET request that shows the form with {% csrf_token %}
        return render(request, 'avg_smogon.html')
def smogon_actual_script(inputText):
    options = Options()
    options.add_argument("--log-level=3")
    options.add_argument('--headless')
    options.add_argument('--disable-gpu')
    options.add_argument('--disable-extensions')
    options.add_argument('--disable-images')
    options.add_argument("--ignore-certificate-errors")
    options.add_experimental_option("excludeSwitches", ["enable-logging"])
    baseURL = "https://pokeapi.co/api/v2/pokemon-species/"
    inputThing = inputText.lower()
    specificURL = baseURL+inputThing
    pokemonData = requests.get(specificURL).json()
    generationData = pokemonData["generation"]
    generationName = generationData["name"]
    generationToBaseURL = {
        "generation-ix": ["https://www.smogon.com/dex/sv/pokemon/"],
        "generation-viii": ["https://www.smogon.com/dex/ss/pokemon/", "https://www.smogon.com/dex/sv/pokemon/"],
        "generation-vii": ["https://www.smogon.com/dex/ss/pokemon/", "https://www.smogon.com/dex/sv/pokemon/", "https://www.smogon.com/dex/sm/pokemon/"],
        "generation-vi": ["https://www.smogon.com/dex/ss/pokemon/", "https://www.smogon.com/dex/sv/pokemon/", "https://www.smogon.com/dex/sm/pokemon/", "https://www.smogon.com/dex/xy/pokemon/"],
        "generation-v": ["https://www.smogon.com/dex/ss/pokemon/", "https://www.smogon.com/dex/sv/pokemon/", "https://www.smogon.com/dex/sm/pokemon/", "https://www.smogon.com/dex/xy/pokemon/", 
                         "https://www.smogon.com/dex/bw/pokemon/"],
        "generation-iv": ["https://www.smogon.com/dex/ss/pokemon/", "https://www.smogon.com/dex/sv/pokemon/", "https://www.smogon.com/dex/sm/pokemon/", "https://www.smogon.com/dex/xy/pokemon/", 
                         "https://www.smogon.com/dex/bw/pokemon/", "https://www.smogon.com/dex/dp/pokemon/"],
        "generation-iii": ["https://www.smogon.com/dex/ss/pokemon/", "https://www.smogon.com/dex/sv/pokemon/", "https://www.smogon.com/dex/sm/pokemon/", "https://www.smogon.com/dex/xy/pokemon/", 
                         "https://www.smogon.com/dex/bw/pokemon/", "https://www.smogon.com/dex/dp/pokemon/",],
        "generation-ii": ["https://www.smogon.com/dex/ss/pokemon/", "https://www.smogon.com/dex/sv/pokemon/", "https://www.smogon.com/dex/sm/pokemon/", "https://www.smogon.com/dex/xy/pokemon/", 
                         "https://www.smogon.com/dex/bw/pokemon/", "https://www.smogon.com/dex/dp/pokemon/",],
        "generation-i": ["https://www.smogon.com/dex/ss/pokemon/", "https://www.smogon.com/dex/sv/pokemon/", "https://www.smogon.com/dex/sm/pokemon/", "https://www.smogon.com/dex/xy/pokemon/", 
                         "https://www.smogon.com/dex/bw/pokemon/", "https://www.smogon.com/dex/dp/pokemon/",],
    }
    driver = webdriver.Chrome(options=options)
    tinyList = []
    for url in generationToBaseURL[generationName]:
        newUrl = url+inputThing
        driver.get(newUrl)
        driver.implicitly_wait(0.25)
        intendedClass = driver.find_element(By.CLASS_NAME, "PokemonAltInfo-data")
        theList = intendedClass.text
        splittedList = theList.split("\n")
        tinyList.append(splittedList[-1])
    driver.quit()
    if "NFE" in tinyList:
        status = ["NFE"]
    elif "LC" in tinyList:
        status = ["LC"]
    else:
        status = [item for item in tinyList if item != "National Dex"]
        for format, number in zip(status,range(len(status))):
            if format == "UUBL":
                status[number] = "OU"
            if format == "NUBL":
                status[number] = "RU"
            if format == "RUBL":
                status[number] = "UU"
            if format == "PUBL":
                status[number] == "NU"
            if format == "ZUBL":
                status[number] == "PU"
    formats = Counter()
    for i in status:
        formats[i] += 1
    return formats

# rb, gs, rs, dp, bw, xy, sm, ss, sv
# Create your views here.

character_data/views.py
from django.http import HttpResponse
from django.template import loader
from .models import Character

def character_data(request):
  mycharacters = list(Character.objects.all().order_by('fullname').values())
  template = loader.get_template('all_characters.html')
  context = {
    'mycharacters': mycharacters,
  }
  return HttpResponse(template.render(context, request))

def details(request, fullname):
  mycharacter = Character.objects.get(fullname=fullname)
  template = loader.get_template('details.html')
  context = {
    'mycharacter': mycharacter,
  }
  return HttpResponse(template.render(context, request))

def muse(request):
  template = loader.get_template('muse.html')
  return HttpResponse(template.render())

def main(request):
  template = loader.get_template('main.html')
  return HttpResponse(template.render())

avg_smogon/templates/avg_smogon.html
{% load static %}
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="{% static 'avg_smogon.css' %}">
<body>

<p>this wont work unless i pay for pythonanywhere but the actual script is on my github</p>

<form action="{% url 'my_smogon_script' %}" method="post">
    {% csrf_token %}
    <input type="text" name="pokemon_input" placeholder="Enter something" required>
    <button type="submit">Click to Calculate Average Format</button>
</form>
<br><br>
{% if result %}
{% for tier, count in result.items %}
<p>{{ tier }} in {{ count }} generations</p>
<br>
{% endfor %}
{% endif %}
<!-- i need to manage that hey, when you load this page, nothin gonna be there. i do think thats the problem! -->
</body>
</html>

character_data/templates/all_characters.html
{% load static %}

<!DOCTYPE html>
<html>
  <link rel="stylesheet" href="{% static 'myfirst.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kalam">
<body>
<title>Aria's Characters</title>
<h1>Characters</h1>
<p><a href="/">Back to home page</a></p>
<p><a href="/muse">Muse info</a></p>
<style>
  .container {
    display: flex;
    align-items: center;
  }

  .container p {
    margin-right: 10px;
  }
</style>
<div class="container">
  <p>Age minimum in years, age must be greater than or equal to the number entered - </p>
<input type="text" id="age_minimum" placeholder="Age Minimum" value=""><br>
</div>
<div class="container">
<p>Age maximum in years, age must be less than or equal to the number entered - </p>
<input type="text" id="age_maximum" placeholder="Age Maximum" value="">
</div>
<div class="container">
<p>Gender selection. Non-binary covers all characters with genders not related to femininity or masculinity -
<select name="gender" id="gender">
  <option value="BLANK">Any</option>
  <option value="Masculine-aligned">Masculine-aligned</option>
  <option value="Feminine-aligned">Feminine-aligned</option>
  <option value="Female">Female</option>
  <option value="Male">Male</option>
  <option value="Non-binary">Non-binary</option>
</select></p>
</div>
<div class="container">
<p>Role selection - </p>
<select name="roles" id="roles">
  <option value="ANY">Any</option>
  <optgroup label="Subjects">
    <option value="ANYSUBJECT">All Subjects</option>
    <option value="Docile">Docile</option>
    <option value="Lahde">Lahde</option>
    <option value="Cronus">Cronus</option>
    <option value="Halcyon">Halcyon</option>
    <option value="Nonviable">Nonviable</option>
  </optgroup>
  <optgroup label="Staff">
    <option value="ANYSTAFF">All Staff</option>
    <option value="Scientist">Scientist</option>
    <option value="Medical Staff">Medical Staff</option>
    <option value="Intern">Intern</option>
  </optgroup>
</select>
</div>
<div class="container">
  <p>Species selection, "human" will give all humans whether they have magic or not -
<select name="species" id="species">
  <option value="ANY">Any</option>
  <option value="Human">Human</option>
  <option value="Non-Magical Human">Non-Magical Human</option>
  <option value="Magical Human">Magical Human</option>
  <option value="Kitsune">Kitsune</option>
  <option value="Angel">Angel</option>
  <option value="Dragon">Dragon</option>
  <option value="Fairy">Fairy</option>
  <option value="Hybrid">Hybrid</option>
  <option value="Other">Other</option>
</select></p>
</div>
<div class="container">
  <p>Orientation selection. Bisexual (F+X) means that character is attracted to both females and gender neutral/non-binary people -
<select name="orientation" id="orientation">
  <option value="ANY">Any</option>
  <option value="Toric">Toric</option>
  <option value="Homoflexible">Homoflexible</option>
  <option value="Lesbian">Lesbian</option>
  <option value="Straight">Straight</option>
  <option value="Bisexual (F+M)">Bisexual (F+M)</option>
  <option value="Bisexual (F+X)">Bisexual (F+X)</option>
  <option value="Pansexual">Pansexual</option>
  <option value="Aroace">Aroace</option>
  <option value="Heteroflexible">Heteroflexible</option>
  <option value="Other">Other</option>
</select></p>
</div>
<div class="container">
  <p>
    Allosexuality selection. Didn't quite get the meaning of allosexuality right, but dunno what else to call it. Yes means that the character has "normal" levels of sexual attraction, no means that the
    character is on the ace spectrum -
    <select name="allosexual" id="allosexual">
      <option value="ANY">Any</option>
      <option value="Yes">Yes</option>
      <option value="No">No</option>
    </select>
  </p>
</div>
<div class="container">
  <p>
    Muse selection, the one you select is the minimum -
    <select name="muse" id="muse">
      <option value=1>Red</option>
      <option value=2>Orange</option>
      <option value=3>Yellow</option>
      <option value=4>Green</option>
      <option value=5>Blue</option>
    </select>
  </p>
</div>
<div class="container">
    <p>
        Submission status. Not super sure about Sycamore and Lilac, but I think the rest are accurate -
        <select name="submitted" id="submitted">
            <option value="ANY">Any</option>
            <option value="Yes">Yes</option>
            <option value="No">No</option>
        </select>
    </p>
</div>
<button onclick="filterCharacters()">Filter</button>
<h2>character results!</h2>
<!-- Display results -->
<ul id="character_list"></ul>
<!-- embed the JSON data -->
{{ mycharacters|json_script:"characters_data" }}
<ul>
  <script>

const includedSpeciesList = ["Human", "Magical Human", "Kitsune", "Angel", "Dragon", "Fairy", "Hybrid","Moonling"]
const includedOrientationList = ["Toric","Homoflexible","Lesbian","Straight","Bisexual (F+M)","Bisexual (F+X)","Pansexual","Aroace","Heteroflexible"]
function filterCharacters() {
  const characters = JSON.parse(document.getElementById('characters_data').textContent);
  const minAge = parseInt(document.getElementById('age_minimum').value) || 0;
  const maxAge = parseInt(document.getElementById('age_maximum').value) || 100000;
  const genderSelected = document.getElementById('gender').value;
  const roleSelected = document.getElementById('roles').value;
  const speciesSelected = document.getElementById('species').value;
  const orientationSelected = document.getElementById('orientation').value;
  const allosexualSelected = document.getElementById('allosexual').value;
  const museSelected = document.getElementById('muse').value;
  const submittedSelected = document.getElementById('submitted').value;
  let filteredList = characters.filter(c => c.age >= minAge && c.age <= maxAge);
  if (genderSelected != "BLANK") {
    filteredList = filteredList.filter(c => c.gender == genderSelected);
  }
  if (roleSelected != "ANY") {
    if (roleSelected == "ANYSTAFF") {
      filteredList = filteredList.filter(c => c.role == "Staff");
    } else if (roleSelected == "ANYSUBJECT") {
      filteredList = filteredList.filter(c => c.role == "Subject");
    } else {
      filteredList = filteredList.filter(c => c.specificRole == roleSelected);
    }
  }
  if (allosexualSelected != "ANY") {
    if (allosexualSelected == "Yes") {
      filteredList = filteredList.filter(c => c.allosexual == true)
    } else {
      filteredList = filteredList.filter(c => c.allosexual == false)
    }
  }
  if (orientationSelected != "ANY") {
    if (orientationSelected == "Other") {
        filteredList = filteredList.filter(c => !includedOrientationList.includes(c.orientation))
    } else {
        filteredList = filteredList.filter(c => c.orientation == orientationSelected);
    }
  }
  if (speciesSelected != "ANY") {
    if (speciesSelected == "Non-Magical Human") {
      filteredList = filteredList.filter(c => c.species == "Human");
    } else if (speciesSelected == "Human") {
      filteredList = filteredList.filter(c => c.species == "Human" || c.species == "Magical Human");
    } else if (speciesSelected == "Other") {
      filteredList = filteredList.filter(c => !includedSpeciesList.includes(c.species))
    } else {
      filteredList = filteredList.filter(c => c.species == speciesSelected);
    }
  }
  filteredList = filteredList.filter(c => c.muse >= museSelected);
  if (submittedSelected != "ANY") {
    if (submittedSelected == "Yes") {
      filteredList = filteredList.filter(c => c.submitted == true)
    } else {
      filteredList = filteredList.filter(c => c.submitted == false)
    }
  }
  const list = document.getElementById('character_list'); // google where it gets this from and how
  list.innerHTML = '';

  filteredList.map(c => {
    list.innerHTML += `<li>${c.fullname} - ${c.role} (${c.specificRole}) - <a href="/details/${c.fullname}">link</a></li>`;
  }).join('');
}
filterCharacters();
  </script>
</ul>

</body>
</html>

character_data/templates/details.html
{% load static %}
<!DOCTYPE html>
<html>
    <link rel="stylesheet" href="{% static 'myfirst.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans">
<body>
<title>{{ mycharacter.fullname }}</title>
<h1>{{ mycharacter.fullname }} </h1>

<p>Age: {{ mycharacter.age }} years old</p>
<p>Species: {{ mycharacter.species}}</p>
<p>Gender: {{ mycharacter.gender }}</p>
<p>Orientation: {{ mycharacter.orientation }}</p>
{% if mycharacter.allosexual == True %}
    <p>Allosexual: Yes</p>
{% else %}
    <p>Allosexual: No</p>
{% endif %}
{% if mycharacter.role == "Subject" %}
    <p>Role: {{ mycharacter.role }}</p>
    <p>Subject Class: {{ mycharacter.specificRole }}</p>
    {% if mycharacter.subjectNumber != 0 %}
        <p>Subject Number: {{ mycharacter.subjectNumber }}</p>
    {% else %}
        <p>Subject Number: Haven't picked one yet</p>
    {% endif %}
{% else %}
    <p>Role: {{ mycharacter.specificRole }}</p>
{% endif %}
<p>Muse: {{ mycharacter.get_muse_display }}</p>
{% if mycharacter.submitted == True %}
    <p>Submitted: Yes</p>
{% else %}
    <p>Submitted: No</p>
{% endif %}
<p>Document: <a href={{ mycharacter.documentLink }}>link</a></p>
<br>
<p>Back to <a href="/character_data">All Characters</a></p>

</body>
</html>

character_data/templates/main.html
<!DOCTYPE html>
<html>
<head>
  <title>My Daystar Characters</title>
</head>
<body>

<p>Check out all my <a href="character_data/">characters</a></p>
<p>Attempt to use my <a href="smogon/avg_smogon/">smogon mess</a></p>

</body>
</html>

character_data/templates/muse.html
{% load static %}

<!DOCTYPE html>
<title>Muse Levels</title>
<html>
  <link rel="stylesheet" href="{% static 'myfirst.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans">
<body>

<h1>Muse</h1>
<p><a href="/character_data/">Back to character search</a></p>
<p>Hello! Here's some information about the muse levels I use on this website.</p>

<p>🔴 - Red muse. This means that if I had to start all over again, I wouldn't be too quick to submit this character. Please don't ask to roleplay with them, the only reason
    I don't drop these is so I don't have to go through the submission process again. (NOTE: If you're reading this before Daystar opens up, atm red is a marker for myself to remember not to submit them,
    or drop them if I have because I have so little motivation)
</p>
<p>🟠 - Orange muse. This means that my muse with this character isn't super high, but I still vibe with them. Please don't ask to roleplay with them, if I feel inspired enough
    to use them for a certain scenario, I'll probably bring it up. I just need something specific to spark my inspiration. I normally write about a paragraph with these characters.
</p>
<p>🟡 - Yellow muse. Generally good for most roleplays. I do actively want to use them and seek out opportunities to use them, but it still
depends on the scenario. Sometimes I'll be happy to write two paragraphs, sometimes I'm just not feeling it. In general,
feel free to ask about these though!
</p>
<p>🟢 - Green muse. High muse, would love to use them! They're good for literate roleplays and I'll rarely say no to using one of these. I can control how much I write with
    these characters and generally enjoy using them.
</p>
<p>🔵 - Blue muse. I often go out of my way to think of a roleplay idea just to use these characters. Do not roleplay with these characters
    if you are not prepared for regular two or more discord message replies. Jokes aside, I ABSOLUTELY LOVE THESE CHARACTERS. PLEASE I AM
    BEGGING YOU ROLEPLAY WITH THEM.
</p>